# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example mousekeyspr'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view,corne_right nice_view_adapter nice_view"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y \nCONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y \nCONFIG_ZMK_SLEEP=y \nCONFIG_ZMK_DISPLAY=y \nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y"]'
      branches: '["zmkfirmware/zmk/main ftc/zmk/mouse-ftc"]'
